### ISSUE TITLE
typeerror for diameter messages without session id

### ISSUE THREAD

**Issue by Freundschaft** [node-diameter/node-diameter#13]
some diameter messages dont have a session id such as device watchdog, etc.
with a change introduced 2 days ago this triggers a typeerror bug.

I made a quick fix here:
https://github.com/Freundschaft/node-diameter/commit/4354ba8946ba8e29dc8a24f2dbe7c46a999fca3c
feel free to merge it.

**Comment by rkovacevic** [comment]
Sry, was busy last week. Fixed now, thx.
