### ISSUE TITLE
GroupedAVP

### ISSUE THREAD

**Issue by misitoth** [node-diameter/node-diameter#15]
Hi,

I just create nodejs application with your diameter module. When diameter-client-app.js receive GroupedAVP throw error (Error: No handler for type: Grouped)
Full stack error message in the attachment.
[dimater_error_groupedAVP.txt](https://github.com/node-diameter/node-diameter/files/269887/dimater_error_groupedAVP.txt)

GroupedAVP description in rfc3588. chapter 4.4 Grouped AVP values

The diameter-types.js var types may include Grouped value encode and decode functions.

**Comment by rkovacevic** [comment]
I pushed a fix in v0.6.4. Sorry for the delay, was busy.
