### ISSUE TITLE
AVP encoding/decoding application/vendor-specificity

### ISSUE THREAD

**Issue by atesgoral** [node-diameter/node-diameter#16]
Take for instance the CC-Request-Type AVP entry in dictionary.json. It's sharing the AVP code 416 with these entries:

```
{
    "code": 416,
    "name": "Not defined in .xml",
    "vendorId": 13019,
    "type": "OctetString",
    "flags": {
        "mandatory": true,
        "protected": false,
        "mayEncrypt": true,
        "vendorBit": true
    }
},
{
    "code": 416,
    "name": "Private-Identity-Request",
    "vendorId": 10415,
    "type": "Integer32",
    "flags": {
        "mandatory": false,
        "protected": false,
        "mayEncrypt": false,
        "vendorBit": true
    },
    "enums": [
        {
            "code": 0,
            "name": "Private identity requested"
        },
        {
            "code": 1,
            "name": "Private identity not requested"
        }
    ]
},
{
    "code": 416,
    "name": "CC-Request-Type",
    "vendorId": 0,
    "type": "Unsigned32",
    "flags": {
        "mandatory": true,
        "protected": true,
        "mayEncrypt": true,
        "vendorBit": false
    },
    "enums": [
        {
            "code": 1,
            "name": "INITIAL_REQUEST"
        },
        {
            "code": 2,
            "name": "UPDATE_REQUEST"
        },
        {
            "code": 3,
            "name": "TERMINATION_REQUEST"
        },
        {
            "code": 4,
            "name": "EVENT_REQUEST"
        }
    ]
},
```

This is causing and issue in my application because the CC-Request-Type AVP erroneously gets mapped to the very first entry with code 416.

Shouldn't `getAvpByCode()` in lib/diameter-dictionary.js be actually something like `getAvpByCodeAndVendorId()` so that it just returns the AVP with the matching vendor ID? For this, the `decodeAvp()` function in lib/diameter-codec.js might have to take in a `vendorId` argument instead of (or in addition to) `appId`. I'm actually also a bit confused about the whole application ID versus vendor ID thing. Are vendor IDs just vendor-specific application IDs and therefore they're the same thing? (i.e. a vendor ID is an application ID?)

**Comment by atesgoral** [comment]
Created PR #17 that handles the decoding issue. Encoding is trickier since there's no way to specify a vendor ID when using an AVP code instead of a name.

**Comment by rkovacevic** [comment]
Great work, thank you! All PRs look good, I'll merge them now and push to NPM.

**Comment by atesgoral** [comment]
@rkovacevic My pleasure! Awesome library, and I needed something like this badly for my project.
