### ISSUE TITLE
Unnecessary usage of hex encoding

### ISSUE THREAD

**Issue by atesgoral** [node-diameter/node-diameter#18]
1. At https://github.com/node-diameter/node-diameter/blob/master/lib/diameter-session.js#L31:

```
var buffer = new Buffer(0, 'hex');
```

The second argument, `'hex'` is redundant because when the first argument is a number, the `new Buffer(size)` overload is used.
1. In diameter-types.js, there are a bunch instances of the same problem as above: `new Buffer(4, 'hex')`, `new Buffer(8, 'hex')`
2. At https://github.com/node-diameter/node-diameter/blob/master/lib/diameter-session.js#L34:

```
buffer = Buffer.concat([buffer, new Buffer(data, 'hex')]);
```

Again, the second argument is probably redundant because `data` is already a Buffer instance.

The only case where there is an encoding argument that is used is this overload:

```
new Buffer(str[, encoding])
```

When the first argument is a string, the second argument determines how bytes are encoded within the string.

**Comment by atesgoral** [comment]
Created #19

**Comment by rkovacevic** [comment]
Merged PR, thx.
