### ISSUE TITLE
Announcement: utility library to make manipulating AVPs easier

### ISSUE THREAD

**Issue by atesgoral** [node-diameter/node-diameter#22]
https://github.com/atesgoral/diameter-avp-object

Brings syntactical sugar (perhaps with some performance cost) by converting nested AVP arrays to nested objects with camelCase properties for more a JavaScripty manipulation of AVPs.

Just plugging it here for the record in case anyone else finds it helpful.

**Comment by rkovacevic** [comment]
Thanks, I saw you working on it, I'll add a link to readme. 

These arrays definitely can't be worked with directly, but the reason I went with arrays, is that AVPs are ordered in diameter, and js objects don't guarantee order of properties. Granted, in all message definitions that I saw, the only time order matters is that "Session-id" needs to be first, but it just seemed ugly to me to hardcode it at the time. 

My other plan was to add some function for accessing the AVPs from arrays. Maybe something similar to how you would select in jQuery. So for example:
`diameter.get('Subscription-Id[0].Subscription-Id-Data', message)`
I may still do something like that, but I'm trying to figure out an elegant way to do it. 

Did you try plugging your library in 'beforeAnyMessage' and 'beforeAnyMessage'? That would probably be the nicest way to work for 99% of cases, and then in those 1%, if ordering is important to someone, he could use the arrays directly.

**Comment by atesgoral** [comment]
Yeah, I thought about first implementing some kind of query logic, but then I was worried about performance and realized that it wouldn't be as sugary as good old dot notation for accessing object properties. Your query idea looks good though.

Ah, I hadn't thought about using the before/after hooks to do this translation behind the scenes. Thanks for the suggestion!
