### ISSUE TITLE
3GPP Gx enum is duplicate within dictionary.xml

### ISSUE THREAD

**Issue by Freundschaft** [node-diameter/node-diameter#3]
I know the standard says the same but the way the lookup is performed its never possible to access this enum:

<enum name="3GPP Gx" code="16777238"/>

because this one is accessed before

<enum name="3GPP Gx" code="16777224"/>

maybe it should also be possible to directly add values by int instead of looking them up in an enum?

**Comment by rkovacevic** [comment]
Dictionaries are copied from Wireshark, I don't maintain it, so if you think something should be changed in them, you should open an issue there, and I'll copy it if they fix it. 

Agreed on feature to set items by integer, I'll implement that next. Thanks for the feedback.

**Comment by Freundschaft** [comment]
From what I got as information form a colleague its different ids for 3GGP Gx Version R8 and Version R6.
R6 uses 16777224 while R8 and up uses 16777238.
So from the standardization (and that's where wireshark gets it information from) there are multiple ids for 3GGP Gx so I assume its just unlucky naming, but the correct fix in node-diameter would be also to allow lookup directly by value

Thanks for the fast feedback! :)

**Comment by rkovacevic** [comment]
Implemented setting by integers. Had to make some api changes, see examples.

**Comment by Freundschaft** [comment]
thanks!
