### ISSUE TITLE
  No function named "getCommandById"

### ISSUE THREAD

**Issue by Naresh-Edla** [node-diameter/node-diameter#33]
I executed client using node-diameter api v0.8 and observed below error.
nodejs diameter-client-example.js 
/home/vuser/nodeDiameterUpdated/node-diameter/lib/diameter-codec.js:114
        command = dictionary.getCommandById(commandName);
                                               ^

TypeError: dictionary.getCommandById is not a function.

It resolved by replacing the line with **command = dictionary.getCommandByCode(commandName);**

var findCommand = function(commandName) {
    var command;
    if (!_.isNumber(commandName)) {
        command = dictionary.getCommandByName(commandName);
    } else {
        //command = dictionary.getCommandById(commandName);
        command = dictionary.getCommandByCode(commandName);
    }
    return command;
};

**Comment by rkovacevic** [comment]
Thanks for catching that, I pushed the fix.
