### ISSUE TITLE
Enumerated AVPs in dictionary should all be UInt32

### ISSUE THREAD

**Issue by rkovacevic** [node-diameter/node-diameter#35]
A lot of them are currently Int32.

**Comment by atesgoral** [comment]
This probably needs to be fixed in node-diameter-dictionary-parser. I'll take a crack at it.

**Comment by atesgoral** [comment]
Int32 seems correct to me. Please see https://github.com/node-diameter/node-diameter/pull/34#issuecomment-295723454

**Comment by atesgoral** [comment]
@rkovacevic Close this if you agree with above?
