### ISSUE TITLE
decodeAvp correct?

### ISSUE THREAD

**Issue by Freundschaft** [node-diameter/node-diameter#4]
I was wondering about this code line:

https://github.com/node-diameter/node-diameter/blob/master/lib/diameter-codec.js#L197

The situation is like this:

I receive a packet with the following content:
![test](https://cloud.githubusercontent.com/assets/5065616/9275112/23ae2102-429b-11e5-86a3-7520ef3abdcb.png)

which results in

diameter_server-2 (err):     at Socket.Readable.push (_stream_readable.js:126:10)
diameter_server-2 (err):     at TCP.onread (net.js:538:20)
diameter_server-2 (err): Error: Unable to find AVP for code 443 for app 16777238
diameter_server-2 (err):     at decodeAvp (/var/node/diameter/node_modules/diameter/lib/diameter-codec.js:199:15)
diameter_server-2 (err):     at decodeAvps (/var/node/diameter/node_modules/diameter/lib/diameter-codec.js:230:19)
diameter_server-2 (err):     at Object.exports.decodeMessage (/var/node/diameter/node_modules/diameter/lib/diameter-codec.js:252:16)
diameter_server-2 (err):     at Socket.DiameterSession.self.socketDataHandler (/var/node/diameter/node_modules/diameter/lib/diameter-session.js:49:45)
diameter_server-2 (err):     at Socket.emit (events.js:107:17)
diameter_server-2 (err):     at readableAddChunk (_stream_readable.js:163:16)
diameter_server-2 (err):     at Socket.Readable.push (_stream_readable.js:126:10)
diameter_server-2 (err):     at TCP.onread (net.js:538:20)

Is it correct to lookup all avps according based on the application id or should only the vendor specific ids be looked up by the specific application id?

**Comment by rkovacevic** [comment]
You are right about vendor IDs, they should be taken into account, I'll add it in the next version, but that's not the reason your request fails. 

Application that you're using, 16777238 (3gpp gx rev 7 I believe), doesn't exist in the dictionary, so you'd need to add it. You could take dictionaries/chargecontrol.xml and just change the app id from 4 to 16777238, but you may have to add some 3gpp specific AVPs, if you're using them. Just delete dictionary.json when you modify dictionaries, to make sure it reparses it. 

Note to self: this should fail with better error message.

**Comment by Freundschaft** [comment]
I am writing by the way some code that will allow to encode vendor ids in AVPs, as soon as I am done I will submit a merge request

**Comment by rkovacevic** [comment]
Thanks. I'm doing some API reshuffling, to make it good finally, so I don't
have to change it anymore. Will try to push that out over the weekend.

On Thu, Aug 20, 2015 at 9:09 PM, Qiong Wu notifications@github.com wrote:

> I am writing by the way some code that will allow to encode vendor ids in
> AVPs, as soon as I am done I will submit a merge request
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/node-diameter/node-diameter/issues/4#issuecomment-133125589
> .

## 

Robert Kovačević

E-mail: robert.kovacevic1@gmail.com
Tel: +385 91 602 7569
Skype: robert.kovacevic1
LinkedIn: http://hr.linkedin.com/in/rkovacevic

**Comment by Freundschaft** [comment]
the implementation is not done yet (some bugs with lengths), but the reading of vendor ids from the dictionaries already works:

https://github.com/Freundschaft/node-diameter/commit/caa6129be3ce494f0480f8ad7129f837dac53304

I will finish it on monday, as I am working on a diameter project in our laboratory, so I can support on some things hopefully :)
