### ISSUE TITLE
Node module is still on V0.9.0

### ISSUE THREAD

**Issue by shokuie** [node-diameter/node-diameter#54]
Seems CD didn't work properly for the latest release (V0.9.1) and node module is still on V0.9.0. Could you please take a look and update.

**Comment by rkovacevic** [comment]
Published 0.9.2:

https://www.npmjs.com/package/diameter

I didn't notice that I forgot to bump the version in package.json, so opening this ticket to improve Travis build script, to fail in these kind of cases:

https://github.com/node-diameter/node-diameter/issues/55
