### ISSUE TITLE
how to do Re Auth Request?

### ISSUE THREAD

**Issue by Freundschaft** [node-diameter/node-diameter#6]
Is it implemented yet that the server sends a request to the client for Re-Auth?

Cheers

**Comment by rkovacevic** [comment]
No, I'm working on that right now. It may be possible with current version,
but it's probably too buggy. Give me few days, it should work with the next
version.

On Fri, Aug 28, 2015 at 4:20 PM, Qiong Wu notifications@github.com wrote:

> Is it implemented yet that the server sends a request to the client for
> Re-Auth?
> 
> Cheers
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/node-diameter/node-diameter/issues/6.

## 

Robert Kovačević

E-mail: robert.kovacevic1@gmail.com
Tel: +385 91 602 7569
Skype: robert.kovacevic1
LinkedIn: http://hr.linkedin.com/in/rkovacevic

**Comment by rkovacevic** [comment]
I redid the API, it's a lot more like other node protocols now, and low level sockets are exposed. Hopefully I won't have to mess with it too much anymore. 

Server initiated messages are working now, you can check how to do it in the examples.
