### ISSUE TITLE
Exception encoding Octet string AVP.

### ISSUE THREAD

**Issue by gczobel** [node-diameter/node-diameter#62]
Encoding an octet string AVP, like Proxy-State, raise an exception:

--------------------------------------------------------------------------------
Unhandled rejection TypeError: "list" argument must be an Array of Buffers
--------------------------------------------------------------------------------    at Function.Buffer.concat (buffer.js:314:13)

This is the message body:
        request.body = request.body.concat([
            ['Proxy-Info', [
                ['Proxy-State', '19']
            ]]
        ]);

Looks that the issue is in the diameter-types.js file. OctetString returns the value, instead of a buffer.

var types = {
    'OctetString': {
        encode: function(value) {
            return value;
        },

**Comment by atesgoral** [comment]
OctetString basically means a Node.js Buffer. Try:

```
['Proxy-State', Buffer.from([19])]
```

**Comment by gczobel** [comment]
Good idea. Thanks.
Using Buffer.from([0,241,16]) work ok.
