### ISSUE TITLE
Dependency update 

### ISSUE THREAD

**Issue by misitoth** [node-diameter/node-diameter#72]
Hi,

Please update lodash package at least >=4.17.5 since npm audit report vulnerabilities in lower version of lodash package..
Complementary library https://github.com/node-diameter/node-diameter-avp-object requires "long@3.2.0" but node-diameter requires only "long@2.2.0". Please sync all node-diameter library dependency.

Thanks

**Comment by atesgoral** [comment]
@misitoth PRs are welcome! But in any case, thanks for bringing this up. I'll see if I can get to it in the next day or two.

**Comment by rkovacevic** [comment]
I pushed the new version with updated deps. Tests are ok, but please yell if you notice something broke.
