### ISSUE TITLE
how to react on client disconnect

### ISSUE THREAD

**Issue by Freundschaft** [node-diameter/node-diameter#8]
server side re-auth works now, but if the client disconnects during the session, the server crashes with
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)

how should disconnecting clients be handled gracefullly?

**Comment by rkovacevic** [comment]
should work now
