### ISSUE TITLE
Session Id for server initiated messages is not correct

### ISSUE THREAD

**Issue by Freundschaft** [node-diameter/node-diameter#9]
If I send a server initiated message, a new session id avp 263 is used for the packet, but it should actually be the same session id as used for other packets, or am I mistaken here?

**Comment by Freundschaft** [comment]
what I did is to overwrite the session id, but I think this should be done generally by the library itself, right?:

var R = require('ramda');
 var formattedBody = R.map(function (entry) {
            return {
              code: entry[0],
              value: entry[1]
            }
          }, event.message.body);
var sessionId = R.find(R.propEq('code', 'Session-Id'))(formattedBody);
request.body = ([
              ['Session-Id', sessionId.value],

**Comment by Freundschaft** [comment]
by the way, I recommend to use bluebird instead of q (https://github.com/petkaantonov/bluebird)

**Comment by rkovacevic** [comment]
Hey, yes, session ID is not being set correctly, I'm working on it. Also the other bug. I'll try to fix it by tomorrow. 

I registered gitter: https://gitter.im/node-diameter/node-diameter
will add it to readme later. 

Agree on bluebird, I had a lot of issues with debugging with Q, and bluebird is supposed to be lot faster.

**Comment by rkovacevic** [comment]
Fixed, please check if it's working correctly for you now.

**Comment by Freundschaft** [comment]
works for me now. thanks!
